# Generated by Django 3.0.6 on 2020-05-23 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200522_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politician_activities',
            name='politician_id',
        ),
        migrations.RemoveField(
            model_name='politician_education',
            name='politician_id',
        ),
        migrations.RemoveField(
            model_name='politicians',
            name='constituency',
        ),
        migrations.RemoveField(
            model_name='politicians',
            name='tags',
        ),
        migrations.AddField(
            model_name='constituency',
            name='politician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Politicians'),
        ),
        migrations.AddField(
            model_name='constituency_category',
            name='constituency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Constituency'),
        ),
        migrations.AddField(
            model_name='country',
            name='politician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Politicians'),
        ),
        migrations.AddField(
            model_name='electoral_positions',
            name='politician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Politicians'),
        ),
        migrations.AddField(
            model_name='parties',
            name='politician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Politicians'),
        ),
        migrations.AddField(
            model_name='politician_activities',
            name='politician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Politicians'),
        ),
        migrations.AddField(
            model_name='politician_education',
            name='politician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Politicians'),
        ),
        migrations.AddField(
            model_name='regions',
            name='politician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Politicians'),
        ),
    ]
