# Generated by Django 3.0.6 on 2020-05-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200523_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicians',
            name='tags',
            field=models.ManyToManyField(to='accounts.Tag'),
        ),
    ]
