# Generated by Django 3.0.6 on 2020-05-23 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_politicians_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constituency',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='constituency',
            name='constituency_id',
        ),
        migrations.RemoveField(
            model_name='constituency',
            name='politician',
        ),
        migrations.RemoveField(
            model_name='constituency',
            name='region_id',
        ),
        migrations.RemoveField(
            model_name='constituency_category',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='country',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='country',
            name='politician',
        ),
        migrations.RemoveField(
            model_name='electoral_positions',
            name='politician',
        ),
        migrations.RemoveField(
            model_name='electoral_positions',
            name='position_id',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='groupId',
        ),
        migrations.RemoveField(
            model_name='parties',
            name='part_id',
        ),
        migrations.RemoveField(
            model_name='parties',
            name='politician',
        ),
        migrations.RemoveField(
            model_name='permissions',
            name='permissionId',
        ),
        migrations.RemoveField(
            model_name='permissions_map',
            name='groupId',
        ),
        migrations.RemoveField(
            model_name='permissions_map',
            name='permissionMapId',
        ),
        migrations.RemoveField(
            model_name='politician_activities',
            name='activity_id',
        ),
        migrations.RemoveField(
            model_name='politician_activities',
            name='politician',
        ),
        migrations.RemoveField(
            model_name='politician_education',
            name='education_id',
        ),
        migrations.RemoveField(
            model_name='politician_education',
            name='politician',
        ),
        migrations.RemoveField(
            model_name='politicians',
            name='party_id',
        ),
        migrations.RemoveField(
            model_name='politicians',
            name='politician_id',
        ),
        migrations.RemoveField(
            model_name='politicians',
            name='position_id',
        ),
        migrations.RemoveField(
            model_name='regions',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='regions',
            name='politician',
        ),
        migrations.RemoveField(
            model_name='regions',
            name='region_id',
        ),
        migrations.RemoveField(
            model_name='systemlogs',
            name='logId',
        ),
        migrations.RemoveField(
            model_name='user_permissions',
            name='groupId',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='groupId',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='users',
            name='groupId',
        ),
        migrations.RemoveField(
            model_name='users',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='users_session',
            name='userId',
        ),
        migrations.AddField(
            model_name='politicians',
            name='activities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Politician_activities'),
        ),
        migrations.AddField(
            model_name='politicians',
            name='constituency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Constituency'),
        ),
        migrations.AddField(
            model_name='politicians',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Country'),
        ),
        migrations.AddField(
            model_name='politicians',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Politician_education'),
        ),
        migrations.AddField(
            model_name='politicians',
            name='electoral_positions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Electoral_positions'),
        ),
        migrations.AddField(
            model_name='politicians',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Parties'),
        ),
        migrations.AddField(
            model_name='politicians',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Regions'),
        ),
        migrations.AlterField(
            model_name='constituency_category',
            name='constituency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Constituency'),
        ),
        migrations.AlterField(
            model_name='politicians',
            name='politician_status',
            field=models.CharField(choices=[('INCUMBENT', 'INCUMBENT'), ('FIRST TIME CONTESTANT', 'FIRST TIME CONTESTANT'), ('CONTESTED BEFORE', 'CONTESTED BEFORE')], max_length=100, null=True),
        ),
    ]
