# Generated by Django 3.0.6 on 2020-05-23 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200523_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissions_map',
            name='permissionId',
        ),
    ]
