# Generated by Django 3.0.6 on 2020-05-23 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_permissions_map_permissionid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electoral_positions',
            options={'verbose_name_plural': 'Electoral_positions'},
        ),
    ]
