# Generated by Django 3.0.6 on 2020-05-23 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200523_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electoral_positions',
            options={'verbose_name_plural': 'Positions'},
        ),
    ]
