# Generated by Django 3.0.6 on 2020-05-28 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200523_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Politician_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorName', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Politician_Category',
            },
        ),
        migrations.AddField(
            model_name='politicians',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Politician_Category'),
        ),
    ]
