# Generated by Django 3.0.6 on 2020-05-28 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200528_0707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='politician_category',
            old_name='categorName',
            new_name='categoryName',
        ),
    ]
