# Generated by Django 3.0.5 on 2020-06-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_politicians_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department_name', models.CharField(blank=True, max_length=500, null=True)),
                ('Dept_create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Dept_update_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='constituency',
            old_name='constituency_create_date',
            new_name='Constituency_create_date',
        ),
        migrations.RenameField(
            model_name='constituency',
            old_name='constituency_female_voters',
            new_name='Constituency_female_voters',
        ),
        migrations.RenameField(
            model_name='constituency',
            old_name='constituency_male_voters',
            new_name='Constituency_male_voters',
        ),
        migrations.RenameField(
            model_name='constituency',
            old_name='constituency_name',
            new_name='Constituency_name',
        ),
        migrations.RenameField(
            model_name='constituency',
            old_name='constituency_polling_stations',
            new_name='Constituency_polling_stations',
        ),
        migrations.RenameField(
            model_name='constituency',
            old_name='constituency_popn',
            new_name='Constituency_popn',
        ),
        migrations.RenameField(
            model_name='constituency',
            old_name='languages',
            new_name='Languages',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='country_add_date',
            new_name='Country_create_date',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='country_female_voters',
            new_name='Country_female_voters',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='country_male_voters',
            new_name='Country_male_voters',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='country_name',
            new_name='Country_name',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='country_polling_stations',
            new_name='Country_popn',
        ),
        migrations.RenameField(
            model_name='electoral_positions',
            old_name='position_create_date',
            new_name='Position_create_date',
        ),
        migrations.RenameField(
            model_name='electoral_positions',
            old_name='position_name',
            new_name='Position_name',
        ),
        migrations.RenameField(
            model_name='parties',
            old_name='party_name',
            new_name='Party_name',
        ),
        migrations.RenameField(
            model_name='politician_education',
            old_name='certificate_name',
            new_name='Certificate_name',
        ),
        migrations.RenameField(
            model_name='politician_education',
            old_name='date_from',
            new_name='Date_from',
        ),
        migrations.RenameField(
            model_name='politician_education',
            old_name='date_to',
            new_name='Date_to',
        ),
        migrations.RenameField(
            model_name='politician_education',
            old_name='school_name',
            new_name='School_name',
        ),
        migrations.RemoveField(
            model_name='parties',
            name='party_create_date',
        ),
        migrations.RemoveField(
            model_name='politicians',
            name='tags',
        ),
        migrations.AddField(
            model_name='constituency',
            name='Constituency_update_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='Delete_status',
            field=models.CharField(choices=[('DELETED', 'DELETED'), ('NOT DELETED', 'NOT DELETED')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='Country_languages',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='Country_political_history',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='Country_polling_stations',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='Country_update_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='electoral_positions',
            name='Position_update_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='parties',
            name='Party_create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='parties',
            name='Party_update_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='politicians',
            name='children',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='politicians',
            name='marital_status',
            field=models.CharField(choices=[('MARRIED', 'MARRIED'), ('SINGLE', 'SINGLE'), ('DIVORCED', 'DIVORCED')], max_length=300, null=True),
        ),
    ]
