# Generated by Django 3.0.8 on 2020-08-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_politician_category_constituency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pollingStation', models.CharField(max_length=200, null=True)),
                ('VotesCasted', models.IntegerField(null=True)),
                ('totalVotes', models.IntegerField(null=True)),
                ('CandidateName', models.CharField(max_length=200, null=True)),
                ('Constituency', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='politicians',
            name='other_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
