# Generated by Django 3.0.8 on 2020-08-21 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_electionresult_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electionresult',
            old_name='image',
            new_name='resultsForm',
        ),
    ]
