# Generated by Django 3.0.8 on 2020-08-21 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20200821_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electionresult',
            name='CandidateName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Politicians'),
        ),
    ]
