# Generated by Django 3.0.8 on 2020-08-21 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20200821_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electionresult',
            name='Constituency',
        ),
    ]
