# Generated by Django 3.0.8 on 2020-08-21 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_electionresult_constituency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electionresult',
            name='electoral_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Electoral_positions'),
        ),
    ]
