# Generated by Django 3.0.8 on 2020-08-22 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20200821_1956'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Groups',
        ),
        migrations.DeleteModel(
            name='Permissions',
        ),
        migrations.DeleteModel(
            name='Permissions_map',
        ),
        migrations.DeleteModel(
            name='Systemlogs',
        ),
        migrations.DeleteModel(
            name='User_permissions',
        ),
    ]
